Traceback (most recent call last):
  File "/home/aboba/Work/Ramesh/Bench/llm_hardware_bench/./response.py", line 251, in <module>
    main()
  File "/home/aboba/Work/Ramesh/Bench/llm_hardware_bench/./response.py", line 248, in main
    get_response(prompt, module, model, outdir, logfile, prompt_strategy)
  File "/home/aboba/Work/Ramesh/Bench/llm_hardware_bench/./response.py", line 125, in get_response
    final_response = generate_verilog(conv, model_type)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aboba/Work/Ramesh/Bench/llm_hardware_bench/./response.py", line 80, in generate_verilog
    return model.generate(conv)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/aboba/Work/Ramesh/Bench/llm_hardware_bench/languagemodels.py", line 74, in generate
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aboba/.local/lib/python3.12/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aboba/.local/lib/python3.12/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/home/aboba/.local/lib/python3.12/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aboba/.local/lib/python3.12/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/aboba/.local/lib/python3.12/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: Internal server error {
    "error": {
        "message": "Internal server error",
        "type": "auth_subrequest_error",
        "param": null,
        "code": "internal_error"
    }
}
 500 {'error': {'message': 'Internal server error', 'type': 'auth_subrequest_error', 'param': None, 'code': 'internal_error'}} {'Date': 'Tue, 30 Jul 2024 16:51:58 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '166', 'Connection': 'keep-alive', 'vary': 'Origin', 'x-request-id': 'req_b239b6040a7c2d1b2071ecf134ce54a8', 'strict-transport-security': 'max-age=15552000; includeSubDomains; preload', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=Ig.UM5EhSInUUcIo5dwtFhOwf8rfgKv95cD66ip8TEY-1722358318-1.0.1.1-eiUvHFym_WBqH_rJR8jGlNL20t5nwmvjrbNyVmUcT3_oA6HM7kEMDgx_eX0eK5leRGE_cE0N0Fdmy0PRPIYe1Q; path=/; expires=Tue, 30-Jul-24 17:21:58 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=qoFlQDE_RYKT7V86CyXSgR9ik0aX87tIDNKOfVfXIgc-1722358318743-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '8ab6db2459e38ce8-EWR', 'alt-svc': 'h3=":443"; ma=86400'}
